const FC27_CHUNKS=['data-pages-01.js','data-pages-02.js','data-pages-03.js','data-pages-04.js','data-pages-05.js','data-pages-06.js','data-pages-07.js','data-pages-08.js'];
const PAGE_IMAGES={
1:[['assets/01_Portada_The_Pitch_Notes_FC27.png',2]],2:[['assets/02_Selected_Highlights_FC27.png',3]],5:[['assets/03_Champs_Token_Store.png',1]],6:[['assets/04_TOTW_Jugador_de_la_Comunidad_Votacion.png',0]],7:[['assets/05_Rareza_y_Cambios_de_Sobres_Cantidades.png',0]],8:[['assets/06_Rareza_y_Cambios_de_Sobres_Venta_Rapida.png',0]],9:[['assets/07_Campaign_Squads_Plantillas_de_Campana.png',5]],11:[['assets/08_Cambios_de_Quimica_ICONOS_y_Heroes.png',0]],12:[['assets/09_ICONOS_Base_Nuevos.png',0]],13:[['assets/10_Salon_de_FUT_Hall_of_FUT.png',0]],16:[['assets/11_SBC_Optimizadas_Jude_Bellingham.png',7]],17:[['assets/12_Item_Scores_Puntuaciones_de_Articulo.png',2]],18:[['assets/13_Salon_de_FUT_Base_Jakub_Blaszczykowski.png',4]],19:[['assets/14_Gallery_Level_Rewards_Recompensas_Nivel_Galeria.png',0]],21:[['assets/15_Season_Pass_Ones_to_Watch_Parte_1.png',0],['assets/16_Season_Pass_Ones_to_Watch_Parte_2.png',0]],22:[['assets/17_Ones_We_Watched_Eventos_en_Vivo.png',5]],23:[['assets/18_Destinados_a_la_Gloria_Jugadores.png',1]],24:[['assets/19_Destinados_a_la_Gloria_Mejora_Atacantes_Mediocampistas.png',0],['assets/20_Destinados_a_la_Gloria_Mejora_Defensas_Porteros.png',0]],25:[['assets/21_The_Grounds.png',2]],27:[['assets/22_European_Nights.png',0],['assets/23_Screaming_Grounds.png',2]],29:[['assets/24_Manager_Live_Desafio_Winning_Squad.png',0]]};
Promise.all(FC27_CHUNKS.map(src=>new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src+'?v=20260915-3';s.onload=resolve;s.onerror=reject;document.head.appendChild(s)}))).then(()=>{
(()=>{
const D={...window.FC27_DATA,pages:(window.FC27_PAGES||[]).flat().map(([page,section,title,rawElements,search])=>({page,section,title,elements:rawElements.map(([type,value])=>type==='i'?{type:'image',src:value}:{type:'text',text:value}),search})).sort((a,b)=>a.page-b.page)};
const app=document.getElementById('app'),nav=document.getElementById('mainNav'),progress=document.getElementById('progress'),toTop=document.getElementById('toTop'),panel=document.getElementById('searchPanel'),input=document.getElementById('globalSearch'),results=document.getElementById('searchResults'),meta=document.getElementById('searchMeta');
const sections=[['inicio','Inicio','home'],['indice','Índice','home'],['fechas','Fechas clave','home'],['fut','FUT','Football Ultimate Team™'],['temporada','Temporada 1','Temporada 1'],['grounds','The Grounds','The Grounds'],['carrera','Modo Carrera','Modo Carrera']];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const slug=s=>s.includes('Football')?'fut':s.includes('Temporada')?'temporada':s.includes('Grounds')?'grounds':s.includes('Carrera')?'carrera':'inicio';
const pageBy=n=>D.pages.find(p=>p.page===Number(n));
function renderNav(){nav.innerHTML=sections.map(([id,label])=>`<a href="#${id}">${esc(label)}</a>`).join('')}
function isHeading(t){return ['Hoja de ruta — Temporadas 1 a 5+','Fechas clave','Tabla de contenidos','EQUIPO DEFINITIVO DE FÚTBOL™','Más control sobre cómo construyes tu club','Posibilidad de intercambio y el Mercado de Transferencias','Recompensas de Fichas de Champions','Jugador de la Comunidad TOTW','Equilibrio de sobres y tienda en el lanzamiento','Actualizaciones de Rareza y Sobres','ARTÍCULOS DE JUGADOR SIGNIFICATIVOS, IMPACTO DURADERO','Obtención de Artículos de Jugador en FUT™','Plantillas de Campaña más enfocadas','Evoluciones','Cambios de Química','ICONOS, Héroes y Salón de FUT™','CADA PARTIDO TE AYUDA A CONSTRUIR TU CLUB','Recompensas posteriores al partido','Modos de juego','Rivales de División','Champions','Batallas de Escuadras','Eventos en Vivo','NUEVAS FORMAS DE UTILIZAR Y GANAR ARTÍCULOS','Artículos Holográficos','SBC optimizadas','Galería','Tienda de Fichas de Galería','Nivel de Galería','Nuevas Colecciones de Galería','TEMPORADA 1: NOVEDADES Y CONTENIDO DE LANZAMIENTO','Acceso Anticipado','Temporada 1: Ones to Watch','Mejoras de jugadores de Ones to Watch','Ones We Watched — Eventos en Vivo para un jugador','Destinados a la Gloria','THE GROUNDS','Entra en The Grounds','Arquetipos','Contenido de The Grounds de la Temporada 1','Eventos en Vivo de The Grounds','European Nights','Screaming Grounds','Las Tiendas de The Grounds','MODO CARRERA','Manager Live','Desafíos de Creadores','ICONOS en Carrera de Jugador y Carrera de Entrenador'].includes(t)}
function block(t){t=t.trim();if(/^●/.test(t))return`<li class="content-block content-bullet">${esc(t.replace(/^●\s*/,''))}</li>`;if(isHeading(t))return`<h4 class="content-heading">${esc(t.replace(/^▌/,'').trim())}</h4>`;if(/^(Más opciones|Preservar lo que|Cada partido ayuda a que|Ritmo de mejora|Mayor flexibilidad)/.test(t)&&t.includes(':')){const i=t.indexOf(':');return`<p class="content-block callout"><strong>${esc(t.slice(0,i+1))}</strong>${esc(t.slice(i+1))}</p>`}return`<p class="content-block">${esc(t)}</p>`}
function image(src,page){return`<figure class="media"><img src="${esc(src)}" alt="Imagen original del documento, página ${page}" data-lightbox="${esc(src)}"><figcaption class="caption">Imagen original · página ${page} · clic para ampliar</figcaption></figure>`}
function table(title,t){return`<div class="table-wrap" aria-label="${esc(title)}"><table><thead><tr>${t.headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${t.rows.map(r=>`<tr>${r.map(c=>`<td>${esc(c)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
function special(n){if(n===3)return table('Fechas clave',{headers:['Hito','Fecha y hora'],rows:D.dates});if(n===7)return table('Rareza y cantidades de Sobres',D.tables.packQuantities);if(n===8)return table('Venta Rápida y rangos',D.tables.quickSell);if(n===19)return table('Recompensas de Nivel de Galería',D.tables.galleryRewards);if(n===24)return table('Mejoras de Destinados a la Gloria — centrocampistas y atacantes',D.tables.destinyAttack)+table('Mejoras de Destinados a la Gloria — defensas y mediocampistas defensivos',D.tables.destinyDefense);return''}
function body(p){const texts=p.elements.filter(e=>e.type==='text').map(e=>e.text),plan=PAGE_IMAGES[p.page]||[],by={};plan.forEach(([src,i])=>(by[i]??=[]).push(src));let out='';for(let i=0;i<=texts.length;i++){if(by[i])out+=by[i].map(src=>image(src,p.page)).join('');if(i===0&&[7,8,19,24].includes(p.page))out+=special(p.page);if(p.page===3&&i===2)out+=special(3);if(i<texts.length)out+=block(texts[i])}return out}
function pageCard(p,open=false){const prev=pageBy(p.page-1),next=pageBy(p.page+1);return`<article class="page-card ${open?'is-open':''}" id="page-${p.page}"><div class="page-head"><div><div class="page-tag">${esc(p.section)}</div><h3>Página ${p.page} · ${esc(p.title)}</h3><p class="page-summary">${esc((p.search||'').slice(0,190))}${(p.search||'').length>190?'…':''}</p></div><button class="btn primary page-toggle" type="button" aria-expanded="${open}" data-toggle-page="${p.page}">${open?'Ocultar contenido':'Ver contenido'} <span>⌄</span></button></div><div class="page-body page-collapsible" ${open?'':'hidden'}>${body(p)}</div>${open?`<div class="page-nav"><button ${prev?'data-page="'+prev.page+'"':'disabled'}>← ${prev?'Página '+prev.page:'Inicio'}</button><button ${next?'data-page="'+next.page+'"':'disabled'}>${next?'Página '+next.page:'Fin'} →</button></div>`:''}</article>`}
function itemsFor(section){return D.pages.filter(p=>p.section===section||(section==='The Grounds'&&p.section==='The Grounds / Modo Carrera')||(section==='Modo Carrera'&&(p.page===28||p.section==='Modo Carrera')))}
function sectionView(section){const items=itemsFor(section),id=slug(section);return`<div class="wrap"><section id="${id}" class="section"><div class="section-head"><div><div class="kicker">${esc(section)}</div><h2>${esc(section)}</h2><p class="section-intro">${items.length} páginas. Pulsa «Ver contenido» para consultar cada página sin convertir la sección en un muro de texto.</p></div><button class="btn" id="sectionSearch">Buscar aquí</button></div><div class="page-stack">${items.map(p=>pageCard(p)).join('')}</div></section></div>`}
function datesView(){return`<div class="wrap"><section id="fechas" class="section"><div class="section-head"><div><div class="kicker">Lanzamiento</div><h2>Fechas clave</h2><p class="section-intro">Consulta cada hito de la tabla original de forma independiente.</p></div></div><div class="date-list">${D.dates.map((d,i)=>`<details class="date-item"><summary><span>${esc(d[0])}</span><b>${esc(d[1])}</b></summary><div>${esc(d[1])}</div></details>`).join('')}</div></section></div>`}
function home(){return`<header id="inicio" class="hero"><div class="hero-inner"><div class="eyebrow">Fuente principal · 14 de septiembre de 2026 · 30 páginas</div><h1>FC 27<br>CONSULTA.</h1><p>Centro de consulta web construido a partir de <strong>EA_SPORTS_FC_27.pdf</strong>. El contenido permanece fiel al documento, pero la navegación ahora prioriza la consulta interactiva.</p><div class="hero-actions"><button class="btn primary" id="heroSearch" type="button">⌕ Buscar en todo</button><a class="btn" href="#indice">Ver índice</a><a class="btn" href="#fechas">Fechas clave</a></div></div></header><div class="wrap"><section class="dashboard"><div class="dashboard-grid"><div class="dash-card dark"><div class="label">Documento fuente</div><div class="big">30 páginas</div><p>Contenido del documento original.</p></div><div class="dash-card"><div class="label">Consulta</div><div class="big">Interactiva</div><p>Abre únicamente el contenido que quieras consultar.</p></div><div class="dash-card"><div class="label">Visual</div><div class="big">24 imágenes</div><p>Conservadas en sus páginas correspondientes.</p></div></div></section><section id="indice" class="section"><div class="section-head"><div><div class="kicker">Mapa</div><h2>Índice</h2><p class="section-intro">Elige una sección para entrar directamente en sus páginas.</p></div></div><div class="toc-grid">${[['Football Ultimate Team™','Páginas 4–19','Football Ultimate Team™'],['Temporada 1','Páginas 20–23','Temporada 1'],['The Grounds','Páginas 24–28','The Grounds'],['Modo Carrera','Páginas 28–29','Modo Carrera'],['Cierre','Página 30','Cierre'],['Todas las páginas','30 páginas','all']].map(([a,b,t])=>`<a class="toc-card" href="${t==='all'?'#documento':'#'+slug(t)}"><strong>${esc(a)}</strong><span>${esc(b)}</span><em>Explorar →</em></a>`).join('')}</div></section></div>${datesView()}${sectionView('Football Ultimate Team™')}${sectionView('Temporada 1')}${sectionView('The Grounds')}${sectionView('Modo Carrera')}${allPages()}`}
function allPages(){return`<div class="wrap"><section id="documento" class="section"><div class="section-head"><div><div class="kicker">Documento completo</div><h2>Todas las páginas</h2><p class="section-intro">30 páginas en formato compacto. Abre solo la que necesites.</p></div></div><div class="all-pages">${D.pages.map(p=>`<details class="compact-page"><summary><span>Página ${p.page} · ${esc(p.title)}</span><small>${esc(p.section)}</small></summary><div class="page-body">${body(p)}</div></details>`).join('')}</div></section></div>`}
function renderPage(n){const p=pageBy(n);if(!p){app.innerHTML=home();bind();return}const related=itemsFor(p.section);app.innerHTML=`<div class="wrap"><section class="section"><div class="section-head"><div><div class="kicker">${esc(p.section)}</div><h2>${esc(p.title)}</h2><p class="section-intro">Página ${p.page} de ${D.meta.pages} · contenido del documento fuente.</p></div><a class="btn" href="#${slug(p.section)}">← Volver a sección</a></div><div class="section-layout"><aside class="section-side"><div class="side-box">${related.map(x=>`<a href="#pagina-${x.page}">P${x.page} · ${esc(x.title)}</a>`).join('')}</div></aside><div class="page-stack">${pageCard(p,true)}</div></div></section></div>`;bind();window.scrollTo({top:0,behavior:'instant'})}
function openSearch(){panel.classList.add('open');panel.setAttribute('aria-hidden','false');setTimeout(()=>input.focus(),20)}function closeSearch(){panel.classList.remove('open');panel.setAttribute('aria-hidden','true')}
function highlight(text,q){const safe=esc(text);if(!q)return safe;const terms=q.trim().split(/\s+/).filter(Boolean).map(x=>x.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'));return safe.replace(new RegExp('('+terms.join('|')+')','ig'),'<mark>$1</mark>')}
function search(q){q=q.trim();if(!q){results.innerHTML='';meta.textContent='Busca en títulos, secciones, párrafos, listas y fechas.';return}const nq=norm(q),m=[];D.pages.forEach(p=>{const h=norm(`${p.title} ${p.section} ${p.search||''}`);if(h.includes(nq)||nq.split(/\s+/).every(x=>h.includes(x)))m.push(p)});meta.textContent=`${m.length} resultado${m.length===1?'':'s'} en ${D.meta.pages} páginas.`;results.innerHTML=m.length?m.map(p=>`<a class="result" href="#pagina-${p.page}"><div class="result-top"><strong>${highlight(p.title,q)}</strong><span>PÁG. ${p.page}</span></div><div class="result-section">${highlight(p.section,q)}</div><div class="result-snippet">${highlight((p.search||p.title).slice(0,230),q)}</div></a>`).join(''):'<div class="search-meta">No se ha encontrado ese término.</div>'}
function bind(){document.querySelectorAll('[data-toggle-page]').forEach(b=>b.onclick=()=>{const card=b.closest('.page-card'),bodyEl=card.querySelector('.page-collapsible'),open=card.classList.toggle('is-open');bodyEl.hidden=!open;b.setAttribute('aria-expanded',open);b.innerHTML=`${open?'Ocultar contenido':'Ver contenido'} <span>⌄</span>`;if(open&&!card.querySelector('.page-nav')){const p=pageBy(b.dataset.togglePage),prev=pageBy(p.page-1),next=pageBy(p.page+1);card.insertAdjacentHTML('beforeend',`<div class="page-nav"><button ${prev?'data-page="'+prev.page+'"':'disabled'}>← ${prev?'Página '+prev.page:'Inicio'}</button><button ${next?'data-page="'+next.page+'"':'disabled'}>${next?'Página '+next.page:'Fin'} →</button></div>`);bind()}});document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{const n=b.dataset.page;history.pushState({},'',`#pagina-${n}`);renderPage(n)});document.querySelectorAll('[data-lightbox]').forEach(img=>img.onclick=()=>{const box=document.createElement('div');box.className='lightbox open';box.innerHTML=`<button aria-label="Cerrar">×</button><img src="${img.src}" alt="${img.alt}">`;document.body.appendChild(box);const close=()=>box.remove();box.querySelector('button').onclick=close;box.onclick=e=>{if(e.target===box)close()}});document.getElementById('heroSearch')?.addEventListener('click',openSearch);document.getElementById('sectionSearch')?.addEventListener('click',openSearch)}
nav.addEventListener('click',()=>nav.classList.remove('mobile-open'));document.getElementById('searchTrigger').onclick=openSearch;document.getElementById('mobileMenu').onclick=()=>nav.classList.toggle('mobile-open');document.getElementById('closeSearch').onclick=closeSearch;input.addEventListener('input',e=>search(e.target.value));panel.addEventListener('click',e=>{if(e.target===panel)closeSearch()});document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openSearch()}if(e.key==='Escape')closeSearch()});window.addEventListener('hashchange',()=>navigate(location.hash));window.addEventListener('scroll',()=>{const h=document.documentElement.scrollHeight-innerHeight;progress.style.width=(h>0?scrollY/h*100:0)+'%';toTop.classList.toggle('show',scrollY>500)});toTop.onclick=()=>scrollTo({top:0,behavior:'smooth'});
function navigate(hash){const h=(hash||location.hash||'#inicio').slice(1);if(h.startsWith('pagina-'))return renderPage(Number(h.slice(7)));app.innerHTML=home();bind();if(h&&h!=='inicio')setTimeout(()=>document.getElementById(h)?.scrollIntoView({behavior:'smooth'}),30)}
renderNav();navigate(location.hash);
})();
}).catch(err=>{document.getElementById('app').innerHTML='<div class="wrap"><section class="section"><h2>No se pudo cargar el contenido</h2><p>Recarga la página para volver a intentarlo.</p></section></div>';console.error(err)});