const FC27_CHUNKS=['data-pages-01.js','data-pages-02.js','data-pages-03.js','data-pages-04.js','data-pages-05.js','data-pages-06.js','data-pages-07.js','data-pages-08.js'];
const PAGE_IMAGES={1:[['assets/01_Portada_The_Pitch_Notes_FC27.png',2]],2:[['assets/02_Selected_Highlights_FC27.png',3]],5:[['assets/03_Champs_Token_Store.png',1]],6:[['assets/04_TOTW_Jugador_de_la_Comunidad_Votacion.png',0]],7:[['assets/05_Rareza_y_Cambios_de_Sobres_Cantidades.png',0]],8:[['assets/06_Rareza_y_Cambios_de_Sobres_Venta_Rapida.png',0]],9:[['assets/07_Campaign_Squads_Plantillas_de_Campana.png',5]],11:[['assets/08_Cambios_de_Quimica_ICONOS_y_Heroes.png',0]],12:[['assets/09_ICONOS_Base_Nuevos.png',0]],13:[['assets/10_Salon_de_FUT_Hall_of_FUT.png',0]],16:[['assets/11_SBC_Optimizadas_Jude_Bellingham.png',7]],17:[['assets/12_Item_Scores_Puntuaciones_de_Articulo.png',2]],18:[['assets/13_Salon_de_FUT_Base_Jakub_Blaszczykowski.png',4]],19:[['assets/14_Gallery_Level_Rewards_Recompensas_Nivel_Galeria.png',0]],21:[['assets/15_Season_Pass_Ones_to_Watch_Parte_1.png',0],['assets/16_Season_Pass_Ones_to_Watch_Parte_2.png',0]],22:[['assets/17_Ones_We_Watched_Eventos_en_Vivo.png',5]],23:[['assets/18_Destinados_a_la_Gloria_Jugadores.png',1]],24:[['assets/19_Destinados_a_la_Gloria_Mejora_Atacantes_Mediocampistas.png',0],['assets/20_Destinados_a_la_Gloria_Mejora_Defensas_Porteros.png',0]],25:[['assets/21_The_Grounds.png',2]],27:[['assets/22_European_Nights.png',0],['assets/23_Screaming_Grounds.png',2]],29:[['assets/24_Manager_Live_Desafio_Winning_Squad.png',0]]};
Promise.all(FC27_CHUNKS.map(src=>new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src+'?v=20260915-8';s.onload=resolve;s.onerror=reject;document.head.appendChild(s)}))).then(()=>{(()=>{
const D={...window.FC27_DATA,pages:(window.FC27_PAGES||[]).flat().map(([page,section,title,rawElements,search])=>({page,section,title,elements:rawElements.map(([type,value])=>type==='i'?{type:'image',src:value}:{type:'text',text:value}),search})).sort((a,b)=>a.page-b.page)};
const app=document.getElementById('app'),nav=document.getElementById('mainNav'),progress=document.getElementById('progress'),toTop=document.getElementById('toTop'),panel=document.getElementById('searchPanel'),input=document.getElementById('globalSearch'),results=document.getElementById('searchResults'),meta=document.getElementById('searchMeta');
const sections=[['inicio','Inicio','home'],['indice','Índice','home'],['fechas','Fechas clave','dates'],['fut','FUT','Football Ultimate Team™'],['temporada','Temporada 1','Temporada 1'],['grounds','The Grounds','The Grounds'],['carrera','Modo Carrera','Modo Carrera']];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const slug=s=>s.includes('Football')?'fut':s.includes('Temporada')?'temporada':s.includes('Grounds')?'grounds':s.includes('Carrera')?'carrera':'inicio';
const pageBy=n=>D.pages.find(p=>p.page===Number(n));
const sectionPages=section=>D.pages.filter(p=>p.section===section||(section==='The Grounds'&&p.section==='The Grounds / Modo Carrera')||(section==='Modo Carrera'&&(p.page>=28||p.section==='Modo Carrera')));
function isHeading(t){return ['Hoja de ruta — Temporadas 1 a 5+','Fechas clave','Tabla de contenidos','EQUIPO DEFINITIVO DE FÚTBOL™','Más control sobre cómo construyes tu club','Posibilidad de intercambio y el Mercado de Transferencias','Recompensas de Fichas de Champions','Jugador de la Comunidad TOTW','Equilibrio de sobres y tienda en el lanzamiento','Actualizaciones de Rareza y Sobres','ARTÍCULOS DE JUGADOR SIGNIFICATIVOS, IMPACTO DURADERO','Obtención de Artículos de Jugador en FUT™','Plantillas de Campaña más enfocadas','Evoluciones','Cambios de Química','ICONOS, Héroes y Salón de FUT™','CADA PARTIDO TE AYUDA A CONSTRUIR TU CLUB','Recompensas posteriores al partido','Modos de juego','Rivales de División','Champions','Batallas de Escuadras','Eventos en Vivo','NUEVAS FORMAS DE UTILIZAR Y GANAR ARTÍCULOS','Artículos Holográficos','SBC optimizadas','Galería','Tienda de Fichas de Galería','Nivel de Galería','Nuevas Colecciones de Galería','TEMPORADA 1: NOVEDADES Y CONTENIDO DE LANZAMIENTO','Acceso Anticipado','Temporada 1: Ones to Watch','Mejoras de jugadores de Ones to Watch','Ones We Watched — Eventos en Vivo para un jugador','Destinados a la Gloria','THE GROUNDS','Entra en The Grounds','Arquetipos','Contenido de The Grounds de la Temporada 1','Eventos en Vivo de The Grounds','European Nights','Screaming Grounds','Las Tiendas de The Grounds','MODO CARRERA','Manager Live','Desafíos de Creadores','ICONOS en Carrera de Jugador y Carrera de Entrenador'].includes(t)}
function block(t){t=t.trim();if(/^●/.test(t))return`<li class="content-block content-bullet">${esc(t.replace(/^●\s*/,''))}</li>`;if(isHeading(t))return`<h4 class="content-heading">${esc(t.replace(/^▌/,'').trim())}</h4>`;if(/^(Más opciones|Preservar lo que|Cada partido ayuda a que|Ritmo de mejora|Mayor flexibilidad)/.test(t)&&t.includes(':')){const i=t.indexOf(':');return`<p class="content-block callout"><strong>${esc(t.slice(0,i+1))}</strong>${esc(t.slice(i+1))}</p>`}return`<p class="content-block">${esc(t)}</p>`}
function image(src,page){return`<figure class="media"><img src="${esc(src)}" alt="Imagen original del documento, página ${page}" data-lightbox="${esc(src)}"><figcaption class="caption">Imagen original · página ${page} · clic para ampliar</figcaption></figure>`}
function table(title,t){return`<div class="table-wrap" aria-label="${esc(title)}"><table><thead><tr>${t.headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${t.rows.map(r=>`<tr>${r.map(c=>`<td>${esc(c)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
function special(n){if(n===3)return table('Fechas clave',{headers:['Hito','Fecha y hora'],rows:D.dates});if(n===7)return table('Rareza y cantidades de Sobres',D.tables.packQuantities);if(n===8)return table('Venta Rápida y rangos',D.tables.quickSell);if(n===19)return table('Recompensas de Nivel de Galería',D.tables.galleryRewards);if(n===24)return table('Mejoras de Destinados a la Gloria — atacantes y centrocampistas',D.tables.destinyAttack)+table('Mejoras de Destinados a la Gloria — defensas y mediocampistas defensivos',D.tables.destinyDefense);return''}
function topicsForPage(p){const texts=p.elements.filter(e=>e.type==='text').map(e=>e.text),topics=[];let start=0;for(let i=0;i<texts.length;i++){if(isHeading(texts[i])&&i>0){if(i>start)topics.push({page:p.page,title:start===0?p.title:texts[start].replace(/^▌/,'').trim(),start,end:i});start=i}}if(start<texts.length)topics.push({page:p.page,title:start===0?p.title:texts[start].replace(/^▌/,'').trim(),start,end:texts.length});return topics.length?topics:[{page:p.page,title:p.title,start:0,end:texts.length}]}
function topicBody(p,topic){const texts=p.elements.filter(e=>e.type==='text').map(e=>e.text),plan=PAGE_IMAGES[p.page]||[];let out='';for(let i=topic.start;i<topic.end;i++)out+=block(texts[i]);if(topic.start===0)plan.forEach(([src])=>{out=image(src,p.page)+out});if(topic.start===0&&[7,8,19,24].includes(p.page))out=special(p.page)+out;if(p.page===3&&topic.start<=2&&topic.end>2)out=special(3)+out;return out}
function allTopics(section){return sectionPages(section).flatMap(p=>topicsForPage(p).map(t=>({...t,section,pageObj:p})))}
function progressFor(){const scroller=document.querySelector('.view-scroll');if(!scroller){progress.style.width='0%';return}const max=scroller.scrollHeight-scroller.clientHeight;progress.style.width=(max>0?Math.min(100,scroller.scrollTop/max*100):0)+'%';toTop.classList.toggle('show',scroller.scrollTop>360)}
function navHtml(active){return sections.map(([id,label])=>`<a href="#${id}" class="${active===id?'active':''}">${esc(label)}</a>`).join('')}
function renderNav(active){nav.innerHTML=navHtml(active);nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')))}
function shell(inner,crumb=''){return`<div class="app-shell"><div class="view-scroll" tabindex="-1">${crumb?`<div class="wrap breadcrumb"><a href="#inicio">Inicio</a><span>›</span><span>${esc(crumb)}</span></div>`:''}${inner}</div></div>`}
function home(){return shell(`<div class="wrap home-view"><section class="hero"><div class="hero-inner"><div class="eyebrow">Fuente principal · 14 de septiembre de 2026 · 30 páginas</div><h1>FC 27<br>CONSULTA.</h1><p>Centro de consulta web construido a partir de <strong>EA_SPORTS_FC_27.pdf</strong>. Navega por interacción: entra en una sección y después abre el contenido concreto que quieras consultar.</p><div class="hero-actions"><button class="btn primary" id="heroSearch" type="button">⌕ Buscar en todo</button><a class="btn" href="#indice">Abrir índice</a><a class="btn" href="#fechas">Fechas clave</a></div></div></section><section class="dashboard"><div class="dashboard-grid"><div class="dash-card dark"><div class="label">Documento fuente</div><div class="big">30 páginas</div><p>Contenido del documento original.</p></div><div class="dash-card"><div class="label">Consulta</div><div class="big">Interactiva</div><p>Las secciones se abren por interacción.</p></div><div class="dash-card"><div class="label">Visual</div><div class="big">24 imágenes</div><p>Conservadas en sus páginas correspondientes.</p></div></div></section><section class="section home-index"><div class="section-head"><div><div class="kicker">Mapa</div><h2>Entrar en una sección</h2><p class="section-intro">No se carga el documento completo en una sola página. Elige dónde quieres entrar.</p></div></div><div class="toc-grid">${[['Football Ultimate Team™','Páginas 4–19','fut'],['Temporada 1','Páginas 20–23','temporada'],['The Grounds','Páginas 24–28','grounds'],['Modo Carrera','Páginas 28–30','carrera'],['Fechas clave','Hitos de lanzamiento','fechas'],['Índice completo','Mapa de navegación','indice']].map(([a,b,t])=>`<a class="toc-card" href="#${t}"><strong>${esc(a)}</strong><span>${esc(b)}</span><em>Entrar →</em></a>`).join('')}</div></section></div>`,'Inicio')}
function pageIndexView(label,section){const pages=sectionPages(section);return shell(`<div class="wrap view-head"><div class="kicker">${esc(label)}</div><h1>${esc(label)}</h1><p class="section-intro">Selecciona un tema o una página. El contenido no aparece hasta que entras en él.</p><div class="topic-grid">${pages.flatMap(p=>topicsForPage(p).map(t=>`<a class="topic-card" href="#tema-${p.page}-${t.start}"><span class="topic-page">P${p.page}</span><strong>${esc(t.title)}</strong><small>${esc(p.title)}</small><em>Consultar →</em></a>`)).join('')}</div></div>`,label)}
function indexView(){return shell(`<div class="wrap view-head"><div class="kicker">Navegación</div><h1>Índice</h1><p class="section-intro">Entra en una sección para ver únicamente sus temas y páginas.</p><div class="topic-grid">${sections.filter(x=>['fut','temporada','grounds','carrera'].includes(x[0])).map(([id,label])=>`<a class="topic-card section-tile" href="#${id}"><strong>${esc(label)}</strong><small>Explorar contenido</small><em>Entrar →</em></a>`).join('')}</div></div>`,'Índice')}
function datesView(){return shell(`<div class="wrap view-head"><div class="kicker">Lanzamiento</div><h1>Fechas clave</h1><p class="section-intro">La tabla de fechas se consulta en su propia pantalla.</p><div class="date-list">${D.dates.map(d=>`<details class="date-item"><summary><span>${esc(d[0])}</span><b>${esc(d[1])}</b></summary><div>${esc(d[1])}</div></details>`).join('')}</div></div>`,'Fechas clave')}
function topicView(page,start){const p=pageBy(page);if(!p)return home();const topic=topicsForPage(p).find(t=>t.start===Number(start))||topicsForPage(p)[0];const list=allTopics(p.section),idx=list.findIndex(x=>x.page===p.page&&x.start===topic.start),prev=idx>0?list[idx-1]:null,next=idx>=0&&idx<list.length-1?list[idx+1]:null;return shell(`<div class="wrap topic-view"><div class="view-head compact"><div class="kicker">${esc(p.section)} · Página ${p.page}</div><h1>${esc(topic.title)}</h1><div class="topic-meta"><span>${esc(p.title)}</span><span>Tema ${idx+1} de ${list.length}</span></div></div><article class="topic-content">${topicBody(p,topic)}</article><div class="topic-actions"><a class="btn" href="#${slug(p.section)}">← Volver a sección</a>${prev?`<a class="btn" href="#tema-${prev.page}-${prev.start}">← Anterior</a>`:''}${next?`<a class="btn primary" href="#tema-${next.page}-${next.start}">Siguiente →</a>`:''}</div></div>`,topic.title)}
function render(){const raw=location.hash.replace(/^#/,'')||'inicio';let view,active='inicio';if(raw==='indice'){view=indexView();active='indice'}else if(raw==='fechas'){view=datesView();active='fechas'}else if(['fut','temporada','grounds','carrera'].includes(raw)){const sec=sections.find(s=>s[0]===raw);view=pageIndexView(sec[1],sec[2]);active=raw}else if(raw.startsWith('tema-')){const [,p,s]=raw.split('-');const page=pageBy(Number(p));active=page?slug(page.section):'inicio';view=topicView(Number(p),Number(s))}else{view=home();active='inicio'}app.innerHTML=view;renderNav(active);bindView();const scroller=document.querySelector('.view-scroll');if(scroller)scroller.scrollTop=0;progressFor()}
function openSearch(){panel.classList.add('open');panel.setAttribute('aria-hidden','false');setTimeout(()=>input.focus(),20)}
function closeSearch(){panel.classList.remove('open');panel.setAttribute('aria-hidden','true')}
function highlight(text,q){const safe=esc(text);if(!q)return safe;const terms=norm(q).split(/\s+/).filter(Boolean).map(x=>x.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'));if(!terms.length)return safe;return safe.replace(new RegExp('('+terms.join('|')+')','ig'),'<mark>$1</mark>')}
function search(q){q=q.trim();if(!q){results.innerHTML='';meta.textContent='Busca en títulos, secciones, párrafos, listas y fechas.';return}const nq=norm(q),m=[];D.pages.forEach(p=>{const topics=topicsForPage(p);const matches=topics.filter(t=>norm([p.title,p.section,p.search||'',p.elements.filter(e=>e.type==='text').slice(t.start,t.end).map(e=>e.text).join(' ')].join(' ')).includes(nq));if(matches.length)m.push({p,t:matches[0]})});meta.textContent=`${m.length} resultado${m.length===1?'':'s'} encontrado${m.length===1?'':'s'}.`;results.innerHTML=m.slice(0,30).map(({p,t})=>`<a class="search-result" href="#tema-${p.page}-${t.start}"><small>Página ${p.page} · ${esc(p.section)}</small><strong>${highlight(t.title,q)}</strong><span>${highlight((p.search||'').slice(0,240),q)}</span></a>`).join('')}
function bindView(){document.querySelectorAll('#app a[href^="#"]').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));document.getElementById('heroSearch')?.addEventListener('click',openSearch);document.getElementById('searchTrigger')?.addEventListener('click',openSearch);document.getElementById('closeSearch')?.addEventListener('click',closeSearch);input?.removeEventListener('input',onSearchInput);input?.addEventListener('input',onSearchInput);panel?.addEventListener('click',onPanelClick);document.getElementById('mobileMenu')?.addEventListener('click',()=>nav.classList.toggle('open'));const scroller=document.querySelector('.view-scroll');scroller?.addEventListener('scroll',progressFor,{passive:true});toTop.onclick=()=>scroller?.scrollTo({top:0,behavior:'smooth'})}
function onSearchInput(e){search(e.target.value)}
function onPanelClick(e){if(e.target===panel)closeSearch()}
render();window.addEventListener('hashchange',render);document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openSearch()}if(e.key==='Escape')closeSearch()});
})()}).catch(err=>{document.getElementById('app').innerHTML='<div class="wrap"><section class="section"><h2>No se pudo cargar el contenido</h2><p class="section-intro">'+String(err?.message||err)+'</p></section></div>';console.error(err)});