const FC27_CHUNKS=['data-pages-01.js','data-pages-02.js','data-pages-03.js','data-pages-04.js','data-pages-05.js','data-pages-06.js','data-pages-07.js','data-pages-08.js'];
Promise.all(FC27_CHUNKS.map(src=>new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=reject;document.head.appendChild(s)}))).then(()=>{
(() => {
  const D = {
    ...window.FC27_DATA,
    pages: (window.FC27_PAGES || []).flat().map(([page,section,title,rawElements,search]) => ({page,section,title,elements:rawElements.map(([type,value]) => type === 'i' ? {type:'image',src:value,alt:`Imagen del documento, página ${page}`} : {type:'text',text:value}),search})).sort((a,b)=>a.page-b.page)
  };
  const app=document.getElementById('app'),nav=document.getElementById('mainNav'),progress=document.getElementById('progress'),toTop=document.getElementById('toTop'),searchPanel=document.getElementById('searchPanel'),searchInput=document.getElementById('globalSearch'),searchResults=document.getElementById('searchResults'),searchMeta=document.getElementById('searchMeta');
  const sections=[['inicio','Inicio','home'],['indice','Índice','home'],['fechas','Fechas clave','home'],['fut','FUT','Football Ultimate Team™'],['temporada','Temporada 1','Temporada 1'],['grounds','The Grounds','The Grounds'],['carrera','Modo Carrera','Modo Carrera'],['documento','Todas las páginas','all']];
  const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const normalize=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
  function sectionSlug(section){if(section.includes('Football'))return'fut';if(section.includes('Temporada'))return'temporada';if(section.includes('Grounds'))return'grounds';if(section.includes('Carrera'))return'carrera';if(section.includes('Fechas'))return'fechas';return'inicio'}
  function pageBy(n){return D.pages.find(p=>p.page===Number(n))}
  function renderNav(){nav.innerHTML=sections.slice(0,7).map(([id,label,type])=>`<a href="#${id}" data-section="${type}" data-target="${id}">${esc(label)}</a>`).join('')}
  function isHeading(text){const t=text.replace(/^▌/,'').trim();return ['Hoja de ruta — Temporadas 1 a 5+','Fechas clave','Tabla de contenidos','EQUIPO DEFINITIVO DE FÚTBOL™','Más control sobre cómo construyes tu club','Posibilidad de intercambio y el Mercado de Transferencias','Recompensas de Fichas de Champions','Jugador de la Comunidad TOTW','Equilibrio de sobres y tienda en el lanzamiento','Actualizaciones de Rareza y Sobres','ARTÍCULOS DE JUGADOR SIGNIFICATIVOS, IMPACTO DURADERO','Obtención de Artículos de Jugador en FUT™','Plantillas de Campaña más enfocadas','Evoluciones','Cambios de Química','ICONOS, Héroes y Salón de FUT™','CADA PARTIDO TE AYUDA A CONSTRUIR TU CLUB','Recompensas posteriores al partido','Modos de juego','Rivales de División','Champions','Batallas de Escuadras','Eventos en Vivo','NUEVAS FORMAS DE UTILIZAR Y GANAR ARTÍCULOS','Artículos Holográficos','SBC optimizadas','Galería','Tienda de Fichas de Galería','Nivel de Galería','Nuevas Colecciones de Galería','TEMPORADA 1: NOVEDADES Y CONTENIDO DE LANZAMIENTO','Acceso Anticipado','Temporada 1: Ones to Watch','Mejoras de jugadores de Ones to Watch','Ones We Watched — Eventos en Vivo para un jugador','Destinados a la Gloria','THE GROUNDS','Entra en The Grounds','Arquetipos','Contenido de The Grounds de la Temporada 1','Eventos en Vivo de The Grounds','European Nights','Screaming Grounds','Las Tiendas de The Grounds','MODO CARRERA','Manager Live','Desafíos de Creadores','ICONOS en Carrera de Jugador y Carrera de Entrenador'].includes(t)}
  function blockHtml(text){const t=text.trim();if(/^●/.test(t))return`<li class="content-block content-bullet">${esc(t.replace(/^●\s*/,''))}</li>`;if(isHeading(t))return`<h4 class="content-heading">${esc(t.replace(/^▌/,'').trim())}</h4>`;if(/^(Más opciones|Preservar lo que|Cada partido ayuda a que|Ritmo de mejora|Mayor flexibilidad)/.test(t)&&t.includes(':')){const idx=t.indexOf(':');return`<p class="content-block callout"><strong>${esc(t.slice(0,idx+1))}</strong>${esc(t.slice(idx+1))}</p>`}return`<p class="content-block">${esc(t)}</p>`}
  function imageHtml(src,page){return`<figure class="media"><img src="${esc(src)}" alt="Imagen original del documento — página ${page}" data-lightbox="${esc(src)}"><figcaption class="caption">Imagen original · página ${page} · clic para ampliar</figcaption></figure>`}
  function tableHtml(title,table){return`<div class="table-wrap" aria-label="${esc(title)}"><table><thead><tr>${table.headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${table.rows.map(r=>`<tr>${r.map(c=>`<td>${esc(c)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
  function specialForPage(page){if(page===3)return tableHtml('Fechas clave',{headers:['Hito','Fecha y hora'],rows:D.dates});if(page===7)return tableHtml('Rareza y cantidades de Sobres',D.tables.packQuantities);if(page===8)return tableHtml('Venta Rápida y rangos',D.tables.quickSell);if(page===19)return tableHtml('Recompensas de Nivel de Galería',D.tables.galleryRewards);if(page===24)return tableHtml('Mejoras de Destinados a la Gloria — centrocampistas y atacantes',D.tables.destinyAttack)+tableHtml('Mejoras de Destinados a la Gloria — defensas y mediocampistas defensivos',D.tables.destinyDefense);return''}
  function pageCard(p,opts={}){let body='',insertedSpecial=false;for(const e of p.elements){if(e.type==='image')body+=imageHtml(e.src,p.page);else body+=blockHtml(e.text);if((p.page===7||p.page===8||p.page===19)&&!insertedSpecial&&e.type==='image'){body+=specialForPage(p.page);insertedSpecial=true}if(p.page===24&&e.type==='image'&&!insertedSpecial){body+=specialForPage(p.page);insertedSpecial=true}}if(p.page===3)body=specialForPage(3)+body;if((p.page===7||p.page===8||p.page===19||p.page===24)&&!insertedSpecial)body+=specialForPage(p.page);const prev=pageBy(p.page-1),next=pageBy(p.page+1);return`<article id="page-${p.page}" class="page-card"><div class="page-head"><div><div class="page-tag">${esc(p.section)}</div><h3>Página ${p.page} · ${esc(p.title)}</h3></div><button class="btn page-open" data-page="${p.page}">Abrir página</button></div><div class="page-body">${body}</div>${opts.nav!==false?`<div class="page-nav"><button ${prev?'data-page="'+prev.page+'"':'disabled'}>← ${prev?'Página '+prev.page:'Inicio'}</button><button ${next?'data-page="'+next.page+'"':'disabled'}>${next?'Página '+next.page:'Fin'} →</button></div>`:''}</article>`}
  function sideNav(items){return`<aside class="section-side"><div class="side-box">${items.map(p=>`<a href="#page-${p.page}">P${p.page} · ${esc(p.title)}</a>`).join('')}</div></aside>`}
  function sectionView(section){const items=D.pages.filter(p=>p.section===section||(section==='The Grounds'&&p.section==='The Grounds / Modo Carrera')||(section==='Modo Carrera'&&(p.page===28||p.section==='Modo Carrera')));const id=sectionSlug(section);return`<div class="wrap"><section id="${id}" class="section"><div class="section-head"><div><div class="kicker">${esc(section)}</div><h2>${esc(section)}</h2><p class="section-intro">${items.length} páginas del documento. El contenido se muestra sin sustituirlo por información externa.</p></div><button class="btn primary" id="sectionSearch">Buscar en esta sección</button></div><div class="section-layout">${sideNav(items)}<div class="page-stack">${items.map(p=>pageCard(p)).join('')}</div></div></section></div>`}
  function homeView(){const quick=[['Football Ultimate Team™','Páginas 4–19','Football Ultimate Team™'],['Temporada 1','Páginas 20–23','Temporada 1'],['The Grounds','Páginas 24–28','The Grounds'],['Modo Carrera','Páginas 28–29','Modo Carrera'],['Cierre','Página 30','Cierre'],['Todas las páginas','30 páginas','all']];return`<header id="inicio" class="hero"><div class="hero-inner"><div class="eyebrow">Fuente principal · 14 de septiembre de 2026 · 30 páginas</div><h1>FC 27<br>CONSULTA.</h1><p>Centro de consulta web construido a partir del documento adjunto <strong>EA_SPORTS_FC_27.pdf</strong>. La interfaz reorganiza la lectura para buscar, navegar y consultar el contenido sin convertirlo en un simple visor PDF.</p><div class="hero-actions"><button class="btn primary" id="heroSearch">⌕ Buscar en todo el documento</button><a class="btn" href="#fechas">Ver fechas clave</a><a class="btn" href="#fut">Entrar en FUT</a></div></div></header><div class="wrap"><section class="dashboard"><div class="dashboard-grid"><div class="dash-card dark"><div class="label">Documento fuente</div><div class="big">30 páginas</div><p>Notas de presentación traducidas al español · 14 de septiembre de 2026.</p></div><div class="dash-card"><div class="label">Consulta</div><div class="big">Global</div><p>Títulos, subtítulos, párrafos, listas y fechas indexadas.</p></div><div class="dash-card"><div class="label">Visual</div><div class="big">24 imágenes</div><p>Imágenes originales asociadas a sus páginas y secciones.</p></div></div></section><section id="indice" class="section"><div class="section-head"><div><div class="kicker">Mapa</div><h2>Acceso directo</h2><p class="section-intro">Navega por los bloques reales del documento o abre todas sus páginas.</p></div></div><div class="toc-grid">${quick.map(([a,b,t])=>`<a class="toc-card" href="${t==='all'?'#documento':'#'+sectionSlug(t)}"><strong>${esc(a)}</strong><span>${esc(b)}</span></a>`).join('')}</div></section><section id="fechas" class="section"><div class="section-head"><div><div class="kicker">Lanzamiento</div><h2>Fechas clave</h2><p class="section-intro">Reproducción estructurada de la tabla de fechas de la página 3.</p></div></div><div class="timeline">${D.dates.map(([a,b])=>`<div class="time-row"><div class="time-date">${esc(b.split(',')[0])}</div><div class="time-card"><strong>${esc(a)}</strong><span>${esc(b)}</span></div></div>`).join('')}</div></section></div>${sectionView('Football Ultimate Team™')}${sectionView('Temporada 1')}${sectionView('The Grounds')}${sectionView('Modo Carrera')}${allPagesView()}`}
  function allPagesView(){return`<div class="wrap"><section class="section" id="documento"><div class="section-head"><div><div class="kicker">Documento completo</div><h2>Todas las páginas</h2><p class="section-intro">Consulta página por página, conservando el orden original.</p></div></div><div class="all-pages">${D.pages.map(p=>`<details class="compact-page"><summary>Página ${p.page} · ${esc(p.title)} <span>${esc(p.section)}</span></summary><div class="page-body">${pageCard(p,{nav:false}).replace(/^<article[^>]*>|<\/article>$/g,'')}</div></details>`).join('')}</div></section></div>`}
  function renderPage(pageNum){const p=pageBy(pageNum);if(!p){app.innerHTML=homeView();bind();return}const related=D.pages.filter(x=>x.section===p.section).slice(0,10);app.innerHTML=`<div class="wrap"><section class="section"><div class="section-head"><div><div class="kicker">${esc(p.section)}</div><h2>${esc(p.title)}</h2><p class="section-intro">Página ${p.page} de ${D.meta.pages} · contenido del documento fuente.</p></div><button class="btn primary" id="backToSection">← Volver a la sección</button></div><div class="section-layout">${sideNav(related)}<div class="page-stack">${pageCard(p)}</div></div></section></div>`;bind();window.scrollTo({top:0,behavior:'instant'})}
  function navigate(hash){const h=(hash||location.hash||'#inicio').replace('#','');if(h.startsWith('pagina-'))return renderPage(Number(h.split('-')[1]));if(h.startsWith('page-'))return renderPage(Number(h.split('-')[1]));if(h==='fut')return app.innerHTML=homeView(),bind(),setTimeout(()=>document.getElementById('fut')?.scrollIntoView(),0);if(h==='temporada')return app.innerHTML=homeView(),bind(),setTimeout(()=>document.getElementById('temporada')?.scrollIntoView(),0);if(h==='grounds')return app.innerHTML=homeView(),bind(),setTimeout(()=>document.getElementById('grounds')?.scrollIntoView(),0);if(h==='carrera')return app.innerHTML=homeView(),bind(),setTimeout(()=>document.getElementById('carrera')?.scrollIntoView(),0);app.innerHTML=homeView();bind();if(h&&h!=='inicio')setTimeout(()=>document.getElementById(h)?.scrollIntoView({behavior:'smooth'}),0)}
  function openSearch(){searchPanel.classList.add('open');searchPanel.setAttribute('aria-hidden','false');setTimeout(()=>searchInput.focus(),30)}function closeSearch(){searchPanel.classList.remove('open');searchPanel.setAttribute('aria-hidden','true')}
  function highlight(text,q){if(!q)return esc(text);const terms=q.trim().split(/\s+/).filter(Boolean).map(x=>x.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'));if(!terms.length)return esc(text);const re=new RegExp('('+terms.join('|')+')','ig');return esc(text).replace(re,m=>`<mark>${m}</mark>`)}
  function search(q){const query=q.trim();if(!query){searchResults.innerHTML='';searchMeta.textContent='Busca títulos, secciones, párrafos, listas y fechas.';return}const nq=normalize(query),matches=[];for(const p of D.pages){const hay=normalize(`${p.title} ${p.section} ${p.search}`);if(hay.includes(nq)||nq.split(/\s+/).every(term=>hay.includes(term))){let source=p.search||p.title,pos=Math.max(0,normalize(source).indexOf(nq)),start=Math.max(0,pos-90),end=Math.min(source.length,pos+170);matches.push({p,snippet:source.slice(start,end)})}}searchMeta.textContent=`${matches.length} resultado${matches.length===1?'':'s'} en ${D.meta.pages} páginas.`;searchResults.innerHTML=matches.length?matches.map(({p,snippet})=>`<a class="result" href="#pagina-${p.page}" data-result-page="${p.page}"><div class="result-top"><div class="result-title">${highlight(p.title,query)}</div><div class="result-page">PÁG. ${p.page}</div></div><div class="result-section">${highlight(p.section,query)}</div><div class="result-snippet">…${highlight(snippet,query)}…</div></a>`).join(''):`<div class="search-meta">No se ha encontrado ese término en el contenido indexado del documento.</div>`}
  function bind(){document.querySelectorAll('[data-page]').forEach(b=>b.addEventListener('click',e=>{const n=e.currentTarget.dataset.page;if(n){history.pushState({},'',`#pagina-${n}`);renderPage(n)}}));document.querySelectorAll('[data-lightbox]').forEach(img=>img.addEventListener('click',()=>{const box=document.createElement('div');box.className='lightbox open';box.innerHTML=`<button aria-label="Cerrar">×</button><img src="${img.src}" alt="${img.alt}">`;document.body.appendChild(box);const close=()=>box.remove();box.querySelector('button').onclick=close;box.onclick=e=>{if(e.target===box)close()};document.addEventListener('keydown',function escKey(e){if(e.key==='Escape'){close();document.removeEventListener('keydown',escKey)}})}));document.getElementById('heroSearch')?.addEventListener('click',openSearch);document.getElementById('sectionSearch')?.addEventListener('click',openSearch);document.getElementById('backToSection')?.addEventListener('click',()=>{const p=pageBy(location.hash.split('-').pop());location.hash=sectionSlug(p?.section||'Inicio')})}
  document.getElementById('searchTrigger').onclick=openSearch;document.getElementById('mobileMenu').onclick=()=>nav.classList.toggle('mobile-open');document.getElementById('closeSearch').onclick=closeSearch;searchInput.addEventListener('input',e=>search(e.target.value));searchPanel.addEventListener('click',e=>{if(e.target===searchPanel)closeSearch()});document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openSearch()}if(e.key==='Escape')closeSearch()});window.addEventListener('hashchange',()=>navigate(location.hash));window.addEventListener('scroll',()=>{const h=document.documentElement.scrollHeight-window.innerHeight;progress.style.width=(h>0?(scrollY/h)*100:0)+'%';toTop.classList.toggle('show',scrollY>500)});toTop.onclick=()=>window.scrollTo({top:0,behavior:'smooth'});renderNav();navigate(location.hash)
})();
});